name: Grading

on:
  pull_request:
    branches: [ master ]

jobs:
  test-group-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 2
          token: ${{ secrets.GH_DB_TOKEN }}
      - name: Make check for an existing utility
        shell: bash
        run: |
          cd "$(git diff --name-only HEAD~1 HEAD)" \
          && [ -z "$(git status --short)" ] \
          && mkdir -p build \
          && cp -p ../7-sorter-utility/sorter ./build/ \
          && [ -n "$(make check -n)" ] \
          && make check \
          && make clean
